FROM node:19

WORKDIR /var/www/app/react-graphql

#COPY src/react-graphql/package*.json .
#
#RUN npm install
#
#COPY src/react-graphql .

EXPOSE 3000

#VOLUME ["./src:/var/www/app"]
#ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
#CMD sh -c "npm install & npm start"
#CMD ["npm", "install"]
