version: "3.5"

services:
    nginx:
      build: ./nginx
      ports:
        - "8080:80"
      volumes:
        - ./nginx/logs:/var/log/nginx

    node:
      build: ./app
      tty: true
      volumes:
        - ./app/src:/var/www/app

    db:
      build: ./db
      ports:
        - "3306:3306"
      # docker-composeのvolumesでマウントするとコピーが作成される？そのせいでmacに._XXXXファイルが作成される
      # その結果再ビルド時に「chown: changing ownership of '/var/lib/mysql/ operation not permitted」が発生する
      # volume mountする際はDockerfile側のVOLUME[]で対応が必要
#      volumes:
#        - ./db/data:/var/lib/mysql
      environment:
        - TZ=JST
        - MYSQL_DATABASE=mariadb
        - MYSQL_USER=mariadb
        - MYSQL_PASSWORD=mariadb
        - MYSQL_ROOT_PASSWORD=mariadb
